[package]
name = "terra-rust-hook"
authors = ["Philipp Schlütermann <philipp.schluetermann@udo.edu>"]
description = "Connect to a webhook to get status updates of terra-rust-bot."
repository = "https://github.com/Philipp-Sc/terra-rust-bot"
version = "0.3.0"
edition = "2021"
 
[[bin]] 
name = "terra-rust-hook"

[dependencies]  
tokio = { version = "1.4", features = ["full"] }
anyhow="1.0"  
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"  
chrono = "0.4"    
regex = "1.5.5" 
slack-hook = "0.8.0"
 


[profile.release]
# Enable link-time optimization, eliminates more code and inlines across crate boundaries.
# Default: false
lto = true

# codegen-units of 1 gives best optimization, but disables parallel building.
# Default: 16
codegen-units = 1

# Includes debug information in release builds. Necessary for profiling. Does not
# slow down the executable.
debug = true

# The default optimization level is 3 for release mode builds.
# 0 means disable optimization and is the default for debug mode buids.
# (Setting opt-level=1 for debug builds is a good way of speeding them up a bit.)
# "s" means optimize for size, "z" reduces size even more.
opt-level = 3