# docker container to help building cosmos_rust_bot packages.

FROM rust:latest

RUN apt-get update && apt-get -y install openssl

WORKDIR /usr/workspace

ENV RUSTFLAGS="--cfg tokio_unstable"
ENV CARGO_HOME=/usr/cargo_home
ENV CARGO_TARGET_DIR=/usr/target

COPY ./helper_build_script.sh /usr/
RUN chmod 755 /usr/helper_build_script.sh

ENTRYPOINT ["/usr/helper_build_script.sh"]
CMD ["test","dev","prod","native","tg-bot","api"]
