# docker container to help run cosmos_rust_bot packages.

FROM rust:slim

WORKDIR /usr/workspace

COPY ./helper_run_script.sh /usr/
RUN chmod 755 /usr/helper_run_script.sh

# settings moved into the /tmp/ volume
#COPY ./workspace/cosmos-rust-bot/cosmos-rust-bot.json .
#COPY ./workspace/cosmos-rust-bot/cosmos-rust-bot-feature-list.json .

#ADD ./workspace/chain-registry /usr/workspace/chain-registry
# add as volume instead

#ENV RUST_BACKTRACE=1

ENTRYPOINT ["/usr/helper_run_script.sh"]
CMD ["dev","prod","native","tg-bot","api"]

