
[package]
name = "cosmos-rust-telegram-bot"
version = "1.0.0"
edition = "2021"


[dependencies]
teloxide = { version = "0.10", features = ["macros"] }
pretty_env_logger = "0.4"
tokio = { workspace = true, features = ["full","rt-multi-thread", "macros"] }

#cosmos-rust-bot = { path = "../../." } # loads the bot_library
cosmos-rust-interface = { workspace = true, default-features = false, features = ["db"] } # only loads the db functionality
#cosmos-rust-interface = { git = "https://github.com/Philipp-Sc/cosmos-rust-interface.git", default-features = false, features = ["db"] } # only loads the db functionality
anyhow.workspace = true
chrono.workspace = true
hex.workspace = true
log.workspace = true
serde_json.workspace = true
regex.workspace = true
heck.workspace = true
sled = { workspace = true, features = ["compression"] }
lazy_static = {workspace = true}

futures = "0.3"
mime_guess = "2.0"
rand = "0.8.5"
url = "2.2.2"