[package]
name = "terra-rust-api-layer"
authors = ["Philipp Schlütermann <philipp.schluetermann@udo.edu>"]
description = "A layer on top of the terra-rust-api to interact with the terra ecosystem."
version = "0.4.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

cosmwasm-std-deprecated = { package = "cosmwasm-std", version = "0.16.7" } # mainly because mirror-protocol is currently incompatible with v1.0.0
cosmwasm-std-latest = { package = "cosmwasm-std", version = "1.0.0" } # for packages that use the latest version // cargo tree

anchor-token = { git = "https://github.com/anchor-protocol/anchor-token-contracts" }
moneymarket = { git = "https://github.com/Anchor-Protocol/money-market-contracts" }
mirror-protocol = { git = "https://github.com/Mirror-Protocol/mirror-contracts" }
astroport = { git = "https://github.com/astroport-fi/astroport-core" }
terraswap = { git = "https://github.com/terraswap/terraswap" }
basset = { git = "https://github.com/lidofinance/lido-terra-contracts" }
#spectrum-protocol = { git = "https://github.com/spectrumprotocol/contracts" } # TODO: figure out why latest version does not compile
cw20 = "0.8.0"
terra-rust-api = "1.2.20"
cosmrs = { path = "../../../cosmos-rust-development/cosmrs", features = ["cosmwasm"] } # "osmosis" features = ["dev"]
cosmos-sdk-proto = { path = "../../../cosmos-rust-development/cosmos-sdk-proto", version = "0.12.2", features = ["grpc-transport", "cosmwasm"] }
osmosis-proto = { path = "../../../cosmos-rust-development/osmosis-proto", features = ["grpc-transport", "osmosis"] }
prost = "0.10"
prost-types = "0.10"
tonic = { version = "0.7.2", features = ["transport"] }
terra-cosmwasm = { version = "1.2" }
tokio = { version = "1.4", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust_decimal = "1.12.2"
rust_decimal_macros = "1.12.2"
secp256k1 = { version = "0.20.3", default-features = false }
reqwest = "0.11.6"
chrono = "0.4"
enum-as-inner = "0.3.3"
cosmwasm-bignumber = "2.2.0"
regex = "1.5.4"
secstr = "0.4.0"
osmo-bindings = { git = "https://github.com/confio/osmosis-bindings" }


[profile.release]
# Enable link-time optimization, eliminates more code and inlines across crate boundaries.
# Default: false
lto = true

# codegen-units of 1 gives best optimization, but disables parallel building.
# Default: 16
codegen-units = 1

# Includes debug information in release builds. Necessary for profiling. Does not
# slow down the executable.
debug = true

# The default optimization level is 3 for release mode builds.
# 0 means disable optimization and is the default for debug mode buids.
# (Setting opt-level=1 for debug builds is a good way of speeding them up a bit.)
# "s" means optimize for size, "z" reduces size even more.
opt-level = 3