[package]
name = "cosmos-rust-signal-bot"
version = "0.4.0"
edition = "2021"


[dependencies]

cosmos-rust-bot = { path = "../../." } # loads the bot_library
cosmos-rust-interface = { path = "../../../cosmos-rust-interface", default-features = false, features = ["db"] } # only loads the db functionality
presage = { git = "https://github.com/whisperfish/presage" }
anyhow = "1.0"
chrono = "0.4"
directories = "3.0"
env_logger = "0.7"
futures = "0.3"
hex = "0.4"
log = "0.4"
mime_guess = "2.0"
rand = "0.7"
serde_json = "1.0"
structopt = "0.3"
tempfile = "3.3"
url = "2.2.2"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "io-std", "io-util"] }
qr2term = { version = "0.2.2" }
regex = "1.6.0"

[patch.crates-io]
"curve25519-dalek" = { git = 'https://github.com/signalapp/curve25519-dalek', branch = 'lizard2' }