[package]
name = "cosmos-rust-server"
version = "0.1.0"
authors = ["Philipp Schlütermann <philipp.schluetermann@udo.edu>"]
description = ""
edition = "2018"

[[bin]]
name = "server"

[dependencies]
cosmos-rust-interface = { workspace = true, default-features = false }

actix-web-httpauth = "*"
actix-cors = "0.6"
actix-service = "2"
actix-web = { version = "4.1", default_features = false, features = ["macros"] }
qstring = "0.7.2"
reqwest = { version = "0.11.12", features = ["json"] }
serde_json = "1.0.87"
serde = { version = "1", features = ["derive"] } 
actix-files = "0.6.2"
